## Q1.

ans - YES 

In [9]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [4]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


## Q2.

In [5]:
for elements in list_:
    print(elements)

1
2
3
4
5


In [6]:
for elements in array_list:
    print(elements)

1
2
3
4
5


## Q3.

In [14]:
array_list = np.array(object = list_, dtype = int)

In [15]:
array_list

array([1, 2, 3, 4, 5])

In [12]:
for e in list_:
    print(type(e))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [16]:
for e in array_list:
    print(type(e))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [17]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

## Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [19]:
num_array.shape

(2, 3)

In [20]:
num_array.size

6

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function. 

In [27]:
matrix = np.zeros((3,3),dtype=np.int8)

In [28]:
matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

## Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [29]:
matrixi = np.eye(5,5)

In [30]:
matrixi

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])